#!/usr/bin/env bash

# This is the a deliver strategy based on rebar3 and relflow
# It uses git push, rebar3 and relflow

# This function must be present since deliver will call it directly
# Everything inside it or around it is up to you
#

run() {
  relflow_versions_init
}
