#!/usr/bin/env bash

# If working directory isn't clean, all changes will be lost if this strategy
# runs all the way to the end. I would be very annoyed if that happened.
#
gitstatus() {
  status "Checking local repository"

  if [ $(git status | grep -c "working directory clean") = 0 ]
  then
    error "
Your working directory is not clean.
Either stash or commit before re-running this command.
Stopping so that uncommitted changes won't be lost.\n"
  fi
}

nothing_to_do() {
  status "Everything up-to-date"
}

authorize_hosts() {
  if [ -n "$HOSTS" ]
  then
    status "Authorizing hosts"

    if [[ ! -e ~/.ssh/known_hosts ]]
    then
      touch ~/.ssh/known_hosts
    fi

    for _host in $HOSTS
    do
      if [[ $(ssh-keygen -F $_host | grep -c found) = 0 ]]
      then
        ssh-keyscan "$_host" 2>/dev/null >> ~/.ssh/known_hosts
      fi
    done
  fi
}

init_app_remotely() {
  __exec_if_defined "pre_init_app_remotely"

  local git_remote="$(git remote -v)"

  status "Ensuring hosts are ready to accept git pushes"

  for _host in $HOSTS_APP_USER
  do
    local _remote_url="$_host:$DELIVER_TO"
    if [[ ! "$git_remote" =~ "$_host $_remote_url" ]]; then
      [[ "$git_remote" =~ "$_host" ]] && git remote rm "$_host"
      git remote add "$_host" "$_remote_url"
    fi
  done

  __remote "
    set -e
    if [ ! -d $DELIVER_TO ]
    then
      mkdir -p $DELIVER_TO
      cd $DELIVER_TO
      git init $SILENCE
      git config receive.denyCurrentBranch ignore
    fi
  "
  __exec_if_defined "post_init_app_remotely"
}

git_push() {
  __exec_if_defined "pre_git_push"

  local _hosts="${1:-"$HOSTS_APP_USER"}"

  status "Pushing new commits with git to: $_hosts"

  background_jobs_pids=()
  background_jobs=()

  for _host in $_hosts
  do
    echo $GIT_PUSH
    local _background_job="git push $GIT_PUSH $_host $REFSPEC $SILENCE"
    __log "JOB: $_background_job"
    ( eval "$_background_job" ) &
    background_jobs_pids+=("$!")
    background_jobs+=("$_background_job")
  done

  __monitor_background_jobs

  __exec_if_defined "post_git_push"
}

git_reset_remote() {
  status "Resetting remote hosts to $REVISION"
  __remote "
    set -e
    cd $DELIVER_TO $SILENCE
    git reset --hard $REVISION $SILENCE
  "
}

git_submodules() {
  __exec_if_defined "pre_git_submodules"

  status "Updating git submodules"
  __remote "
    set -e
    cd $DELIVER_TO $SILENCE
    git submodule init $SILENCE
    git submodule sync $SILENCE
    if [ -e .gitmodules ]
    then
      if [ ! -e ~/.ssh/known_hosts ]
      then
        touch ~/.ssh/known_hosts
      fi
      cat .gitmodules | awk -F '://|@|:|/' '
      /url =/ {
        command=\"test \$(ssh-keygen -F \" \$2 \" | grep -c found) = 0 && ssh-keyscan \" \$2 \" >> ~/.ssh/known_hosts $SILENCE\"
        system(command)
        close(command)
      }'
      git submodule foreach 'git reset --hard $SILENCE' $SILENCE
      git submodule update $SILENCE
    fi
  "

  __exec_if_defined "post_git_submodules"
}

rvmrc_trust() {
  if [ -e "$ORIGIN_DIR/.rvmrc" ]
  then
    __exec_if_defined "pre_rvmrc_trust"

    status "Trusting rvmrc in $DELIVER_TO"
    __remote "
      set -e
      source ~/.profile
      rvm rvmrc trust $DELIVER_TO $SILENCE
    "

    __exec_if_defined "post_rvmrc_trust"
  fi
}

authorize_remote_hosts() {
  if [[ ${#AUTHORIZED_REMOTE_HOSTS[@]} != 0 ]]
  then
    status "Authorizing remote hosts"
    __remote "
      set -e
      source ~/.profile
      for _remote_host in $AUTHORIZED_REMOTE_HOSTS
      do
        if [[ \$(ssh-keygen -F \$_remote_host | grep -c found) = 0 ]]
        then
          ssh-keyscan \$_remote_host >> ~/.ssh/known_hosts $SILENCE
        fi
      done
    "
  fi
}

bundle_install() {
  __exec_if_defined "pre_bundle_install"

  status "Installing gems with bundler"
  __remote "
    set -e
    source ~/.profile
    cd $DELIVER_TO $SILENCE
    if [[ \$APP_ENV = production ]] || [[ \$RACK_ENV = production ]] || [[ \$RAILS_ENV = production ]]
    then
      bundle install --local --deployment --without development test $SILENCE
    else
      bundle install --local --deployment $SILENCE
    fi
  "

  __exec_if_defined "post_bundle_install"
}

npm_install() {
  __exec_if_defined "pre_npm_install"

  status "Installing modules with npm"
  __remote "
    set -e
    source ~/.profile
    cd $DELIVER_TO $SILENCE
    npm install $SILENCE
  "

  __exec_if_defined "post_npm_install"
}

pre_rebar3_release_tar() {
  VER=`cat rebar.config | grep relflow-release-version-marker | cut -d'%' -f1 | sed s/\"//g | sed s/\ //g`
}

rebar3_release_tar() {
  __exec_if_defined "pre_rebar3_release_tar"
  status "Rebar3 create release tar"
  __remote '
    export REFSPEC='"'$REFSPEC'"'
    export APP_NAME='"'$APP_NAME'"'
    export DELIVER_TO='"'$DELIVER_TO'"'
    export VER='"'$VER'"'
    export DEPLOY_TO='"'$DEPLOY_TO'"'
    export GROUP='"'$GROUP'"'
    export ERLANG_ENV='"'$ERLANG_ENV'"'
    export GIT_EMAIL='"'$GIT_EMAIL'"'
    export GIT_USER='"'$GIT_USER'"'
    export GIT_REMOTE='"'$GIT_REMOTE'"'
    git config --global push.default simple
    source ~/.bashrc
    cd   $DELIVER_TO
    git checkout $REFSPEC
    git remote add origin $GIT_REMOTE
    rebar3 as $ERLANG_ENV release tar
    mkdir -p "$DEPLOY_TO/releases/$VER"
    cp "_build/$ERLANG_ENV/rel/$APP_NAME/$APP_NAME-$VER.tar.gz" "$DEPLOY_TO/releases/$VER/$APP_NAME.tar.gz"
    cd $DEPLOY_TO
    tar xfv "releases/$VER/$APP_NAME.tar.gz"
  '
  __exec_if_defined "post_rebar3_initial_release"
}

pre_generate_relapp() {
  export VER=`cat rebar.config | grep relflow-release-version-marker | cut -d'%' -f1 | sed s/\"//g | sed s/\ //g`
  export GIT_REMOTE=`git remote get-url origin`
}

generate_relapp() {
  __exec_if_defined "pre_generate_relapp"

  status "Relflow generate relapp"
  __remote '
    export APP_NAME='"'$APP_NAME'"'
    export DELIVER_TO='"'$DELIVER_TO'"'
    export VER='"'$VER'"'
    export DEPLOY_TO='"'$DEPLOY_TO'"'
    export GROUP='"'$GROUP'"'
    export ERLANG_ENV='"'$ERLANG_ENV'"'
    export GIT_EMAIL='"'$GIT_EMAIL'"'
    export GIT_USER='"'$GIT_USER'"'
    export GIT_REMOTE='"'$GIT_REMOTE'"'
    source ~/.bashrc
    cd $DELIVER_TO
    git config user.email $GIT_EMAIL
    git config user.name  $GIT_USER
    git checkout master
    rebar3 as $ERLANG_ENV relflow -u "v$VER"
    rebar3 as $ERLANG_ENV release relup -u $VER
    rebar3 as $ERLANG_ENV release tar
    NEWVER=`cat rebar.config | grep relflow-release-version-marker | cut -d'%' -f1 | sed s/\"//g | sed s/\ //g`
    mkdir -p "$DEPLOY_TO/release/$APP_NAME/$NEWVER"
    cp "_build/$ERLANG_ENV/rel/$APP_NAME/$APP_NAME-$NEWVER.tar.gz" "$DEPLOY_TO/release/$APP_NAME/$NEWVER"/$APP_NAME.tar.gz
  '
  __exec_if_defined "post_generate_relapp"
}

post_generate_relapp() {
  VER=`cat rebar.config | grep relflow-release-version-marker | cut -d'%' -f1 | sed s/\"//g | sed s/\ //g`
  REFSPEC=v"$VER"
}

generate_rebar_relapp() {
  status "Generate relapp"
  __remote '
    export APP_NAME='"'$APP_NAME'"'
    export DELIVER_TO='"'$DELIVER_TO'"'
    export VER='"'$VER'"'
    export DEPLOY_TO='"'$DEPLOY_TO'"'
    export GROUP='"'$GROUP'"'
    export ERLANG_ENV='"'$ERLANG_ENV'"'
    export GIT_EMAIL='"'$GIT_EMAIL'"'
    export GIT_USER='"'$GIT_USER'"'
    source ~/.bashrc
    cd $DELIVER_TO
    git config user.email $GIT_EMAIL
    git config user.name $GIT_USER
    git checkout master
    rebar3 as $ERLANG_ENV release tar
    mkdir -p "$DEPLOY_TO/releases/$VER"
    cp "_build/$ERLANG_ENV/rel/$APP_NAME/$APP_NAME-$VER.tar.gz" "$DEPLOY_TO/releases/$VER/$APP_NAME.tar.gz"
    tar -xf "$DEPLOY_TO/releases/$VER/$APP_NAME.tar.gz" -C "$DEPLOY_TO/releases/$VER/"
    rm "$DEPLOY_TO/current"
    ln -s "$DEPLOY_TO/releases/$VER/" "$DEPLOY_TO/current"
  '
}

# rebar3 as staging release relup -u 20170107.122137 where 20170107.122137 is the deployed version
# REFSPEC=20170107.122137 rebar3 as staging release relup -u $REFSPEC
generate_relup() {
  __exec_if_defined "pre_generate_relup"

  status "Relflow generate relup"
  __remote '
    source ~/.bashrc
    export APP_NAME='"'$APP_NAME'"'
    export DELIVER_TO='"'$DELIVER_TO'"'
    export DEPLOY_TO='"'$DEPLOY_TO'"'
    export VER='"'$VER'"'
    export GIT_EMAIL='"'$GIT_EMAIL'"'
    export GIT_USER='"'$GIT_USER'"'
    cd $DELIVER_TO
    rebar3 as staging relup -u "$VER"
    rebar3 as staging release tar
    mkdir -p "$DEPLOY_TO/releases/$VER"
    cp "_build/staging/rel/$APP_NAME/$APP_NAME-$VER.tar.gz" "$DEPLOY_TO/releases/$VER/$APP_NAME.tar.gz"
    cd $DEPLOY_TO
    #bin/$APP_NAME install $VER
  '
  __exec_if_defined "post_generate_relup"
}

foreman_export() {
  __exec_if_defined "pre_foreman_export"

  status "Exporting services to $SUPERVISOR"
  local _foreman="foreman export $SUPERVISOR tmp --user $APP_USER --app $APP"
  test -n "$PORT" && _foreman="$_foreman --port $PORT"
  test -n "$FOREMAN_EXTRAS" && _foreman="$_foreman $FOREMAN_EXTRAS"

  __remote "
    set -e
    source ~/.profile
    cd $DELIVER_TO $SILENCE
    $_foreman $SILENCE
  "

  __exec_if_defined "post_foreman_export"
}

launch() {
  __exec_if_defined "pre_launch"

  status "Launching app with $SUPERVISOR"
  # This command, because of the sudo dependency, will use your local $USER.
  # You should be able to log in with $USER to the remote servers, and you
  # should be able to run sudo without needing a password.
  #
  # I will be tackling this shortly, you really shouldn't neeed sudo
  # privileges to deliver an app. What was I thinking?!?
  if [[ "$SUPERVISOR" == "bluepill" ]]; then
    __remote "
      set -e
      sudo bluepill ${APP} status | grep up && sudo bluepill ${APP} stop $SILENCE
      sudo bluepill load $DELIVER_TO/tmp/${APP}.pill $SILENCE
      " "$HOSTS"
  elif [[ "$SUPERVISOR" == "smf" ]]; then
    __remote "
      set -e
      sudo svccfg import $DELIVER_TO/tmp/${APP}*xml $SILENCE
      svcs -H -o FMRI $APP/* | xargs -I {} sudo svcadm enable -t {} $SILENCE
      svcs -H -o FMRI $APP/* | xargs -I {} sudo svcadm restart {} $SILENCE
    " "$HOSTS"
  else
    __remote "
      set -e
      if [[ \$(sudo initctl list | awk '/^'$APP' / { print \$0 }') =~ 'run' ]]; then
        sudo stop $APP $SILENCE
      fi
      sudo rm -f /etc/init/$APP[.-]*
      sudo mv -f $DELIVER_TO/tmp/*conf /etc/init/
      sudo start $APP $SILENCE
    " "$HOSTS"
  fi

  __exec_if_defined "post_launch"
}

# Aliased, no longer bound to upstart
#
upstart() {
  __exec_if_defined "pre_upstart"
  launch
  __exec_if_defined "post_upstart"
}

permissions() {
  __exec_if_defined "pre_permissions"

  status "Setting file permissions"
  __remote "
    [ -n \"$OWNER\" ] && sudo chown -fR $OWNER.$GROUP $DELIVER_TO
    [ -n \"$PERMISSIONS\" ] && sudo chmod -fR $PERMISSIONS $DELIVER_TO
    exit 0
  " "$HOSTS"

  __exec_if_defined "post_permissions"
}
